services:
  datn-env:
    image: ${IMAGE_NAME:-datn-rl-env:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-datn_rl_env}
    working_dir: /workspace/DATN
    stdin_open: true
    tty: true
    volumes:
      - ${DATN_PATH}:/workspace/DATN
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - DREAMPLACE_HOME=/opt/DREAMPlace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
